### ISSUE TITLE
Releases Search by MBID's artist

### ISSUE THREAD

**Issue by papposilene** [XenosEleatikos/MusicBrainz#2]
Hi everyone, 

I am creating an application using this very useful library. But, by creating a script to look for the releases with a MBID's artist, I encountered a "Call to undefined method MusicBrainz\Value\SearchResult\Release::setReleaseFromArray()" bug. 

I finally fixed it by adding an -s at every "release" in the file Value/SearchResult/Release.php

`<?php`

`namespace MusicBrainz\Value\SearchResult;`

`use MusicBrainz\Value\Property\ReleasesTrait;`
`use MusicBrainz\Value\SearchResult;`

/**
 * A list of results from the search API
 */
`class Release extends SearchResult`
`{`
`    use ReleasesTrait;`

    /**
     * Constructs a list of results from the search API.
     *
     * @param array $searchResult A search result from the search API
     */
`    public function __construct(array $searchResult = [])`
`    {`
`        $this->setReleasesFromArray($searchResult, null);`
`        parent::__construct($searchResult);`
`    }`

    /**
     * Returns the search result as string.
     *
     * @return string
     */
`    public function __toString(): string`
`    {`
`        return $this->getRelease();`
`    }`
`}`

Indeed, the Value/Property/ReleaseTrait.php file hasn't a "setReleaseFromArray" function.

I now have a "ReleaseListPage" response with the result of a search based on MBID's artist, but each Release's element is empty... I don't if I used the library in a wrong way or if it's a bug needing a fix...

**Comment by XenosEleatikos** [comment]
Hey there,
sorry for this. I currently do not have this library in use for myself, so testing and bug tracking is always welcome :-)
Please have a look at my latest commit in master: 737525902a97c91216928b3d54318336de4aafdd
It's late and before the weekend I will not have the time to have a closer look at this issue and to write a unit test. So I just hope it works and helps you. Otherwise you'll have to wait until the weekend.
So, sorry again and let me know if there are still problems.
Christoph

**Comment by XenosEleatikos** [comment]
Hi again,
please pull and try again. It should work now. I added unit tests for the search release method and committed some bug fixes.
